### ISSUE TITLE
google map library not found!

### ISSUE THREAD

**Issue by kurtobando** [bharatpe/g-mapify#22]
Hello author, 

Issue:
`google map library not found!`

Behavior:
The said error returns if I call GMapify component twice from a functional component.

Screenshot:
![image](https://user-images.githubusercontent.com/38178537/107304254-b0a58c00-6abb-11eb-8743-74444236b4ab.png)

**Comment by krishpe** [comment]
@sandeep-r-bharatpe

**Comment by sandeep-r-bharatpe** [comment]
@kurtobando Thanks for notify us for this issue, we give enhancement to inject **g-mapify** more then one time.
